Updated MkDocs GitHub workflow to extract semantic versioning and dynamically deploy using `mike deploy` on branch feature/DPAV-1838

diff --git a/.github/workflows/publish-mkdocs.yml b/.github/workflows/publish-mkdocs.yml
--- a/.github/workflows/publish-mkdocs.yml
+++ b/.github/workflows/publish-mkdocs.yml
@@ -21,8 +21,8 @@ jobs:
 #         VERSION=$(echo "$SOURCE_BRANCH" | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')
           VERSION=1.0.5
           if [ -z "$VERSION" ]; then
-             echo "Error - No semantic release version found in source branch: $SOURCE_BRANCH"
-             exit 1
+               echo "Error - No semantic release version found in source branch: $SOURCE_BRANCH"
+               exit 1
           fi
 
           echo "VERSION=$VERSION" >> $GITHUB_ENV
